### ISSUE TITLE
"./nebula -s" is not working

### ISSUE THREAD

**Issue by thallys97** [libra-php/nebula#2]
The command "./nebula -s" is not working, I use the Windows operating system, and I'm using Git Bash. Inside the "nebula" folder, I enter the command "./nebula -s" in Git Bash; however, the local server is not running. However, in Git Bash, when I enter the command "./bin/serve" in the "nebula" directory, the local server for Nebula runs.

**Comment by whleucka** [comment]
Hey there! 

Thanks for the opening the issue. I will take a look at that immediately. 
I am on Linux only, so I appreciate the report for Windows OS.

Running the 'nebula' symlink works for me in Linux (also tried it in a docker instance) 

I am curious if there is any output at all? Also, can you try running ./bin/nebula instead of the symlink? Thank you!

**Comment by thallys97** [comment]
In the root folder "nebula," I enter the following commands in the Git Bash terminal:

./bin/serve  ===> This command makes the local server run, but when I try to access the URL "http://localhost:8888/" in the Chrome browser, it shows me a fatal error.


./nebula -s   ===> It doesn't work, I receive the following message in the terminal: "Unknown option(s) provided. Use -h or --help for help."

./bin/nebula  ===> It doesn't work, I receive the following message in the terminal:  "Unknown option(s) provided. Use -h or --help for help."

./nebula -h   ===>  It doesn't work, I receive the following message in the terminal: "Unknown option(s) provided. Use -h or --help for help."

./bin/nebula -h   ===> It works as shown in the screenshot.



![2023-08-10](https://github.com/libra-php/nebula/assets/60667295/9e52dfb9-fc77-4d95-b929-ff23ac087ac7)


![2023-08-10 (1)](https://github.com/libra-php/nebula/assets/60667295/decaec0f-336e-4a62-a412-a11cef95502b)


![2023-08-10 (2)](https://github.com/libra-php/nebula/assets/60667295/6355b07e-3699-487a-a506-f64fe225c294)



![2023-08-10 (3)](https://github.com/libra-php/nebula/assets/60667295/8560bc86-5213-4685-81f6-2ff879aae024)


"Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente"  ===>  "No connection could be made because the target machine actively refused it."

**Comment by whleucka** [comment]
The connection error is due to Redis. It appears that the Redis connection cannot be established on 6379. I think you'd need to install the dependencies to get Redis working. I haven't got around to creating the documentation for that section yet, and Redis is a new feature for rate limiting requests and caching responses.

Redis can be disabled in `src/Config/Redis.php`
![image](https://github.com/libra-php/nebula/assets/71740767/8304dcce-29e5-4ca4-8bf3-ebd3ce6d3180)

I am not exactly sure why the symlink is not working for you. I might consider just moving the nebula CLI to the app root instead. 

![image](https://github.com/libra-php/nebula/assets/71740767/da72cc97-6fd0-43bc-9498-ee3d1dac9369)

Can you pull the latest changes and try disabling Redis to see if you can get the dev server up and running?

**Comment by whleucka** [comment]
When I investigated symlinks + git + windows, it turns out there could be a problem. 

![image](https://github.com/libra-php/nebula/assets/71740767/5bebeded-9e5d-495a-a05c-8ab5f35db7dc)
![image](https://github.com/libra-php/nebula/assets/71740767/b06d99c2-f107-4a52-968b-2f3e8da80c69)

I am not sure how git is configured on your machine. I have never used WSL. Perhaps there is a fix? 

![image](https://github.com/libra-php/nebula/assets/71740767/ae8da6e1-bc2e-4a95-8512-1694ae76c046)

**Comment by whleucka** [comment]
In regard to Redis, I have decided to default disabled. 
The .env.example defaults have been updated. I have also updated the configs. 

The main README has been updated with some documentation. 
Hopefully that will get you going!

Cheers

**Comment by thallys97** [comment]
It worked, with the update you made to the repository there was no error when starting the server using the command "./bin/serve".

![2023-08-10 (5)](https://github.com/libra-php/nebula/assets/60667295/3ee12245-dde3-4cac-a916-0905791d5c96)

I know what WSL is, but I've never used it. Later, I'll learn how it works to see if I can run the command "./nebula -s" on it.

**Comment by whleucka** [comment]
Thanks for letting me know! Sorry, I confused Git Bash with WSL, my bad. However, it might run better in a Linux environment—but that is awesome that it is working on Windows!
